# Generated by Django 6.0.4 on 2026-04-24 04:35

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('moderator', 'moderator'), ('master', 'master'), ('user', 'user')], default='user', max_length=9)),
                ('first_name', models.CharField(default='Anonymous', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(default='Anonymous', max_length=150, verbose_name='Фамилия')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Аватар')),
                ('phone', models.CharField(blank=True, max_length=35, null=True, verbose_name='Номер телефона')),
                ('telegram', models.CharField(blank=True, max_length=150, null=True, verbose_name='Аккаунт телеграм')),
                ('max_messenger', models.CharField(blank=True, max_length=150, null=True, verbose_name='Аккаунт МАХ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Состояние аккаунта')),
                ('experience', models.IntegerField(blank=True, default=0, null=True, verbose_name='Опыт (лет)')),
                ('education', models.CharField(blank=True, max_length=500, null=True, verbose_name='Образование')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('portfolio', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Портфолио')),
                ('is_master_approved', models.BooleanField(default=False, verbose_name='Профиль мастера подтверждён')),
                ('categories', models.ManyToManyField(blank=True, to='services.category', verbose_name='Категории услуг')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
