# Generated by Django 6.0.4 on 2026-04-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),  # Добавляем зависимость от services
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, to='services.Category', verbose_name='Категории услуг'),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Опыт (лет)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_master_approved',
            field=models.BooleanField(default=False, verbose_name='Профиль мастера подтверждён'),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Портфолио'),
        ),
    ]
