# Generated by Django 6.0.4 on 2026-04-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_master_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Город/Адрес'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_days',
            field=models.CharField(blank=True, default='Пн-Сб: 09:00-18:00, Вс: выходной', max_length=200, null=True, verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Опыт (лет)'),
        ),
    ]
