# Generated by Django 6.0.4 on 2026-04-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_location_user_work_days_alter_user_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание деятельности'),
        ),
    ]
