# Generated by Django 6.0.4 on 2026-04-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('icon', models.CharField(default='fas fa-image', max_length=50, verbose_name='Иконка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Прошла модерацию')),
                ('is_main', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание услуги')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Фотография')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (₽)')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Город/Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность объявления')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('archived', 'Архивирована')], default='active', max_length=20, verbose_name='Статус')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', verbose_name='Фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное фото')),
            ],
            options={
                'verbose_name': 'фото услуги',
                'verbose_name_plural': 'фото услуг',
            },
        ),
    ]
