# Generated by Django 6.0.4 on 2026-04-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='Шаблон услуги'),
        ),
    ]
