# Generated by Django 6.0.4 on 2026-04-24 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_is_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title'], 'verbose_name': 'услуга (шаблон)', 'verbose_name_plural': 'услуги (библиотека)'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='service',
            name='location',
        ),
        migrations.RemoveField(
            model_name='service',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='service',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='views',
        ),
        migrations.AddField(
            model_name='service',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_template',
            field=models.BooleanField(default=True, verbose_name='Шаблон услуги'),
        ),
        migrations.CreateModel(
            name='MasterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (₽)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_services', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
                ('service_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'услуга мастера',
                'verbose_name_plural': 'услуги мастеров',
                'ordering': ['-created_at'],
                'unique_together': {('master', 'service_template')},
            },
        ),
    ]
