# Generated by Django 6.0.4 on 2026-04-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_category_icon_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fas fa-wrench', max_length=50, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
    ]
