# Generated by Django 6.0.4 on 2026-04-24 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('services', '0005_alter_service_options_remove_service_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
        migrations.AddField(
            model_name='review',
            name='master_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.masterservice', verbose_name='Услуга мастера'),
            preserve_default=False,
        ),
    ]
